INSERT INTO livro (qtde_paginas, id_livro, autor, editora, titulo) VALUES
    (320, 1, 'Machado de Assis', 'Penguin Companhia', 'Dom Casmurro'),
(416, 2, 'Gabriel García Márquez', 'Record', 'Cem Anos de Solidão'),
(96, 3, 'Antoine de Saint-Exupéry', 'Agir', 'O Pequeno Príncipe'),
(328, 4, 'George Orwell', 'Companhia das Letras', '1984'),
(576, 5, 'J.R.R. Tolkien', 'Martins Fontes', 'O Senhor dos Anéis: A Sociedade do Anel'),
(432, 6, 'Jane Austen', 'Martin Claret', 'Orgulho e Preconceito'),
(480, 7, 'Aluísio Azevedo', 'Livraria Garnier', 'O Cortiço'),
(160, 8, 'Graciliano Ramos', 'Record', 'Vidas Secas'),
(264, 9, 'J.K. Rowling', 'Rocco', 'Harry Potter e a Pedra Filosofal'),
(112, 10, 'Franz Kafka', 'Antofágica', 'A Metamorfose'),
(448, 11, 'Harper Lee', 'José Olympio', 'O Sol é Para Todos'),
(928, 12, 'Miguel de Cervantes', 'Nova Fronteira', 'Dom Quixote'),
(256, 13, 'Machado de Assis', 'Ateliê Editorial', 'Memórias Póstumas de Brás Cubas'),
(448, 14, 'Emily Brontë', 'Penguin Companhia', 'O Morro dos Ventos Uivantes'),
(336, 15, 'J.R.R. Tolkien', 'Martins Fontes', 'O Hobbit'),
(152, 16, 'George Orwell', 'Companhia das Letras', 'A Revolução dos Bichos'),
(328, 17, 'José Saramago', 'Companhia das Letras', 'Ensaio Sobre a Cegueira'),
(1248, 18, 'Alexandre Dumas', 'Zahar', 'O Conde de Monte Cristo'),
(688, 19, 'Fiódor Dostoiévski', 'Editora 34', 'Crime e Castigo'),
(234, 20, 'J.D. Salinger', 'Little, Brown and Company', 'O Apanhador no Campo de Centeio');